nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        # Autorise le navigateur à envoyer/recevoir les cookies cross-origin.
        # Indispensable pour le cookie JWT httpOnly. À coupler avec
        # credentials:'include' côté fetch React.
        allow_credentials: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
